name: Run Python tests

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
  pull_request:
    paths:
      - "python/**"
  workflow_dispatch:


permissions:
  contents: read

jobs:
  test_and_quality_check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11","3.12","3.13"]
    env:
      PYTHON: "${{ matrix.python-version }}"
    permissions:
      contents: read  # checkout code only
    defaults:
      run:
        working-directory: python

    steps:
    - name: Checkout repository
      uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

    - name: Set up Python
      uses: actions/setup-python@2bd53f9a4d1dd1cd21eaffcc01a7b91a8e73ea4c
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r test_requirements.txt

    - name: Code format and linter with Ruff
      run: make code-quality

    - name: Run tests
      run: make test
